run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude errcheck from test files
    - linters:
        - errcheck
      path: integration_test\.go
    
    # Exclude ineffassign from test files
    - linters:
        - ineffassign
      path: integration_test\.go

